server:
  http:
    addr: 127.0.0.1:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    user: root
    password: 82AF916059F13E331E633AC0B8A8191B
    host: 14.103.143.229
    port: 3306
    database: wl_playform
  redis:
    addr: 14.103.143.229:6379
    password: 82AF916059F13E331E633AC0B8A8191B
    db: 0
  mongodb:
    user: mongo_CAFJCH
    password: mongo_KSrmMC
    host: 14.103.143.229
    port: 27107
    database: hummingbird
