server:
  http:
    addr: 127.0.0.1:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    user: root
    password: badb6fe15b05b84863ff1e2b249deab2
    host: 14.103.243.15
    port: 3306
    database: hummingbird
  redis:
    addr: 14.103.243.15:6379
    password: badb6fe15b05b84863ff1e2b249deab2
    db: 0
  mongodb:
    user: mongo_CAFJCH
    password: mongo_KSrmMC
    host: 14.103.243.15
    port: 27107
    database: hummingbird
