// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: api/dashboard/v1/dashboard.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewRequest) Reset() {
	*x = OverviewRequest{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewRequest) ProtoMessage() {}

func (x *OverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewRequest.ProtoReflect.Descriptor instead.
func (*OverviewRequest) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

type OverviewReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductTotal       int32                  `protobuf:"varint,1,opt,name=product_total,json=productTotal,proto3" json:"product_total,omitempty"`
	ProductPublished   int32                  `protobuf:"varint,2,opt,name=product_published,json=productPublished,proto3" json:"product_published,omitempty"`
	ProductUnpublished int32                  `protobuf:"varint,3,opt,name=product_unpublished,json=productUnpublished,proto3" json:"product_unpublished,omitempty"`
	DeviceTotal        int32                  `protobuf:"varint,4,opt,name=device_total,json=deviceTotal,proto3" json:"device_total,omitempty"`
	DeviceOnline       int32                  `protobuf:"varint,5,opt,name=device_online,json=deviceOnline,proto3" json:"device_online,omitempty"`
	DeviceOffline      int32                  `protobuf:"varint,6,opt,name=device_offline,json=deviceOffline,proto3" json:"device_offline,omitempty"`
	DriverTotal        int32                  `protobuf:"varint,7,opt,name=driver_total,json=driverTotal,proto3" json:"driver_total,omitempty"`
	DriverRunning      int32                  `protobuf:"varint,8,opt,name=driver_running,json=driverRunning,proto3" json:"driver_running,omitempty"`
	DriverStopped      int32                  `protobuf:"varint,9,opt,name=driver_stopped,json=driverStopped,proto3" json:"driver_stopped,omitempty"`
	AlarmTotal         int32                  `protobuf:"varint,10,opt,name=alarm_total,json=alarmTotal,proto3" json:"alarm_total,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OverviewReply) Reset() {
	*x = OverviewReply{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewReply) ProtoMessage() {}

func (x *OverviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewReply.ProtoReflect.Descriptor instead.
func (*OverviewReply) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *OverviewReply) GetProductTotal() int32 {
	if x != nil {
		return x.ProductTotal
	}
	return 0
}

func (x *OverviewReply) GetProductPublished() int32 {
	if x != nil {
		return x.ProductPublished
	}
	return 0
}

func (x *OverviewReply) GetProductUnpublished() int32 {
	if x != nil {
		return x.ProductUnpublished
	}
	return 0
}

func (x *OverviewReply) GetDeviceTotal() int32 {
	if x != nil {
		return x.DeviceTotal
	}
	return 0
}

func (x *OverviewReply) GetDeviceOnline() int32 {
	if x != nil {
		return x.DeviceOnline
	}
	return 0
}

func (x *OverviewReply) GetDeviceOffline() int32 {
	if x != nil {
		return x.DeviceOffline
	}
	return 0
}

func (x *OverviewReply) GetDriverTotal() int32 {
	if x != nil {
		return x.DriverTotal
	}
	return 0
}

func (x *OverviewReply) GetDriverRunning() int32 {
	if x != nil {
		return x.DriverRunning
	}
	return 0
}

func (x *OverviewReply) GetDriverStopped() int32 {
	if x != nil {
		return x.DriverStopped
	}
	return 0
}

func (x *OverviewReply) GetAlarmTotal() int32 {
	if x != nil {
		return x.AlarmTotal
	}
	return 0
}

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

type ResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        float64                `protobuf:"fixed64,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Load          float64                `protobuf:"fixed64,3,opt,name=load,proto3" json:"load,omitempty"`
	Disk          float64                `protobuf:"fixed64,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReply) Reset() {
	*x = ResourceReply{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReply) ProtoMessage() {}

func (x *ResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReply.ProtoReflect.Descriptor instead.
func (*ResourceReply) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceReply) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceReply) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ResourceReply) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *ResourceReply) GetDisk() float64 {
	if x != nil {
		return x.Disk
	}
	return 0
}

type AlarmStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmStatRequest) Reset() {
	*x = AlarmStatRequest{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmStatRequest) ProtoMessage() {}

func (x *AlarmStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmStatRequest.ProtoReflect.Descriptor instead.
func (*AlarmStatRequest) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

type AlarmStatReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlarmTotal     int32                  `protobuf:"varint,1,opt,name=alarm_total,json=alarmTotal,proto3" json:"alarm_total,omitempty"`
	AlarmHandled   int32                  `protobuf:"varint,2,opt,name=alarm_handled,json=alarmHandled,proto3" json:"alarm_handled,omitempty"`
	AlarmUnhandled int32                  `protobuf:"varint,3,opt,name=alarm_unhandled,json=alarmUnhandled,proto3" json:"alarm_unhandled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlarmStatReply) Reset() {
	*x = AlarmStatReply{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmStatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmStatReply) ProtoMessage() {}

func (x *AlarmStatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmStatReply.ProtoReflect.Descriptor instead.
func (*AlarmStatReply) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *AlarmStatReply) GetAlarmTotal() int32 {
	if x != nil {
		return x.AlarmTotal
	}
	return 0
}

func (x *AlarmStatReply) GetAlarmHandled() int32 {
	if x != nil {
		return x.AlarmHandled
	}
	return 0
}

func (x *AlarmStatReply) GetAlarmUnhandled() int32 {
	if x != nil {
		return x.AlarmUnhandled
	}
	return 0
}

type DeviceMessageCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMessageCountRequest) Reset() {
	*x = DeviceMessageCountRequest{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMessageCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMessageCountRequest) ProtoMessage() {}

func (x *DeviceMessageCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMessageCountRequest.ProtoReflect.Descriptor instead.
func (*DeviceMessageCountRequest) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceMessageCountRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *DeviceMessageCountRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type DeviceMessageCountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMessageCountReply) Reset() {
	*x = DeviceMessageCountReply{}
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMessageCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMessageCountReply) ProtoMessage() {}

func (x *DeviceMessageCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashboard_v1_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMessageCountReply.ProtoReflect.Descriptor instead.
func (*DeviceMessageCountReply) Descriptor() ([]byte, []int) {
	return file_api_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceMessageCountReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_dashboard_v1_dashboard_proto protoreflect.FileDescriptor

const file_api_dashboard_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	" api/dashboard/v1/dashboard.proto\x12\fdashboard.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fOverviewRequest\"\x93\x03\n" +
	"\rOverviewReply\x12#\n" +
	"\rproduct_total\x18\x01 \x01(\x05R\fproductTotal\x12+\n" +
	"\x11product_published\x18\x02 \x01(\x05R\x10productPublished\x12/\n" +
	"\x13product_unpublished\x18\x03 \x01(\x05R\x12productUnpublished\x12!\n" +
	"\fdevice_total\x18\x04 \x01(\x05R\vdeviceTotal\x12#\n" +
	"\rdevice_online\x18\x05 \x01(\x05R\fdeviceOnline\x12%\n" +
	"\x0edevice_offline\x18\x06 \x01(\x05R\rdeviceOffline\x12!\n" +
	"\fdriver_total\x18\a \x01(\x05R\vdriverTotal\x12%\n" +
	"\x0edriver_running\x18\b \x01(\x05R\rdriverRunning\x12%\n" +
	"\x0edriver_stopped\x18\t \x01(\x05R\rdriverStopped\x12\x1f\n" +
	"\valarm_total\x18\n" +
	" \x01(\x05R\n" +
	"alarmTotal\"\x11\n" +
	"\x0fResourceRequest\"a\n" +
	"\rResourceReply\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x01R\x06memory\x12\x12\n" +
	"\x04load\x18\x03 \x01(\x01R\x04load\x12\x12\n" +
	"\x04disk\x18\x04 \x01(\x01R\x04disk\"\x12\n" +
	"\x10AlarmStatRequest\"\x7f\n" +
	"\x0eAlarmStatReply\x12\x1f\n" +
	"\valarm_total\x18\x01 \x01(\x05R\n" +
	"alarmTotal\x12#\n" +
	"\ralarm_handled\x18\x02 \x01(\x05R\falarmHandled\x12'\n" +
	"\x0falarm_unhandled\x18\x03 \x01(\x05R\x0ealarmUnhandled\"U\n" +
	"\x19DeviceMessageCountRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\"/\n" +
	"\x17DeviceMessageCountReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xdf\x03\n" +
	"\tDashboard\x12g\n" +
	"\bOverview\x12\x1d.dashboard.v1.OverviewRequest\x1a\x1b.dashboard.v1.OverviewReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/dashboard/overview\x12g\n" +
	"\bResource\x12\x1d.dashboard.v1.ResourceRequest\x1a\x1b.dashboard.v1.ResourceReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/dashboard/resource\x12l\n" +
	"\tAlarmStat\x12\x1e.dashboard.v1.AlarmStatRequest\x1a\x1c.dashboard.v1.AlarmStatReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/dashboard/alarm-stat\x12\x91\x01\n" +
	"\x12DeviceMessageCount\x12'.dashboard.v1.DeviceMessageCountRequest\x1a%.dashboard.v1.DeviceMessageCountReply\"+\x82\xd3\xe4\x93\x02%\x12#/api/dashboard/device-message-countB.Z,IOT_Hummingbird_back_end/api/dashboard/v1;v1b\x06proto3"

var (
	file_api_dashboard_v1_dashboard_proto_rawDescOnce sync.Once
	file_api_dashboard_v1_dashboard_proto_rawDescData []byte
)

func file_api_dashboard_v1_dashboard_proto_rawDescGZIP() []byte {
	file_api_dashboard_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_api_dashboard_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dashboard_v1_dashboard_proto_rawDesc), len(file_api_dashboard_v1_dashboard_proto_rawDesc)))
	})
	return file_api_dashboard_v1_dashboard_proto_rawDescData
}

var file_api_dashboard_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_dashboard_v1_dashboard_proto_goTypes = []any{
	(*OverviewRequest)(nil),           // 0: dashboard.v1.OverviewRequest
	(*OverviewReply)(nil),             // 1: dashboard.v1.OverviewReply
	(*ResourceRequest)(nil),           // 2: dashboard.v1.ResourceRequest
	(*ResourceReply)(nil),             // 3: dashboard.v1.ResourceReply
	(*AlarmStatRequest)(nil),          // 4: dashboard.v1.AlarmStatRequest
	(*AlarmStatReply)(nil),            // 5: dashboard.v1.AlarmStatReply
	(*DeviceMessageCountRequest)(nil), // 6: dashboard.v1.DeviceMessageCountRequest
	(*DeviceMessageCountReply)(nil),   // 7: dashboard.v1.DeviceMessageCountReply
}
var file_api_dashboard_v1_dashboard_proto_depIdxs = []int32{
	0, // 0: dashboard.v1.Dashboard.Overview:input_type -> dashboard.v1.OverviewRequest
	2, // 1: dashboard.v1.Dashboard.Resource:input_type -> dashboard.v1.ResourceRequest
	4, // 2: dashboard.v1.Dashboard.AlarmStat:input_type -> dashboard.v1.AlarmStatRequest
	6, // 3: dashboard.v1.Dashboard.DeviceMessageCount:input_type -> dashboard.v1.DeviceMessageCountRequest
	1, // 4: dashboard.v1.Dashboard.Overview:output_type -> dashboard.v1.OverviewReply
	3, // 5: dashboard.v1.Dashboard.Resource:output_type -> dashboard.v1.ResourceReply
	5, // 6: dashboard.v1.Dashboard.AlarmStat:output_type -> dashboard.v1.AlarmStatReply
	7, // 7: dashboard.v1.Dashboard.DeviceMessageCount:output_type -> dashboard.v1.DeviceMessageCountReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_dashboard_v1_dashboard_proto_init() }
func file_api_dashboard_v1_dashboard_proto_init() {
	if File_api_dashboard_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dashboard_v1_dashboard_proto_rawDesc), len(file_api_dashboard_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dashboard_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_api_dashboard_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_api_dashboard_v1_dashboard_proto_msgTypes,
	}.Build()
	File_api_dashboard_v1_dashboard_proto = out.File
	file_api_dashboard_v1_dashboard_proto_goTypes = nil
	file_api_dashboard_v1_dashboard_proto_depIdxs = nil
}
