// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.19.4
// source: equipment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEquipmentProductsList = "/equipment.v1.Equipment/ProductsList"

type EquipmentHTTPServer interface {
	// ProductsList Sends a greeting
	ProductsList(context.Context, *ProductsListReq) (*ProductsListResp, error)
}

func RegisterEquipmentHTTPServer(s *http.Server, srv EquipmentHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/ProductsList", _Equipment_ProductsList0_HTTP_Handler(srv))
}

func _Equipment_ProductsList0_HTTP_Handler(srv EquipmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProductsListReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEquipmentProductsList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProductsList(ctx, req.(*ProductsListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProductsListResp)
		return ctx.Result(200, reply)
	}
}

type EquipmentHTTPClient interface {
	ProductsList(ctx context.Context, req *ProductsListReq, opts ...http.CallOption) (rsp *ProductsListResp, err error)
}

type EquipmentHTTPClientImpl struct {
	cc *http.Client
}

func NewEquipmentHTTPClient(client *http.Client) EquipmentHTTPClient {
	return &EquipmentHTTPClientImpl{client}
}

func (c *EquipmentHTTPClientImpl) ProductsList(ctx context.Context, in *ProductsListReq, opts ...http.CallOption) (*ProductsListResp, error) {
	var out ProductsListResp
	pattern := "/v1/ProductsList"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEquipmentProductsList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
